In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [35]:
%time

py_questions = pd.read_csv('pythonquestions/Questions.csv', encoding='iso-8859-1', 
                    parse_dates=True)
py_answers = pd.read_csv('pythonquestions/Answers.csv', encoding='iso-8859-1',
                    parse_dates=True)
py_tags = pd.read_csv('pythonquestions/Tags.csv')

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.96 µs

    Id        Tag
0  469     python
1  469        osx
2  469      fonts
3  469  photoshop
4  502     python

In [38]:
%time

r_questions = pd.read_csv('rquestions/Questions.csv', encoding='iso-8859-1',
                          parse_dates=True)
r_answers = pd.read_csv('rquestions/Answers.csv', encoding='iso-8859-1',
                        parse_dates=True)
r_tags = pd.read_csv('rquestions/Tags.csv')

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 8.11 µs

In [20]:
py_questions.head()

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...
3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...

In [41]:
display(HTML(py_questions.loc[1001, 'Body']))

In [42]:
py_questions.sort_values('Score', ascending=False).head(10)

,Id,OwnerUserId,CreationDate,Score,Title,Body
962,231767,18300.0,2008-10-23T22:21:11Z,5524,"What does the ""yield"" keyword do?",<p>What is the use of the <code>yield</code> k...
334,100003,9951.0,2008-09-19T06:10:46Z,3219,What is a metaclass in Python?,<p>What are metaclasses? What do you use them ...
291,82831,15616.0,2008-09-17T12:55:00Z,2729,How do I check whether a file exists using Pyt...,"<p>How do I check whether a file exists, witho..."
1874,394809,51518.0,2008-12-27T08:32:18Z,2655,Does Python have a ternary conditional operator?,<p>If Python does not have a ternary condition...
306,89228,17085.0,2008-09-18T01:35:30Z,2312,Calling an external command in Python,<p>How can I call an external command (as if I...
2018,419163,51518.0,2009-01-07T04:11:00Z,2184,"What does `if __name__ == ""__main__"":` do?","<p>What does the <code>if __name__ == ""__main_..."
4086,739654,1897.0,2009-04-11T07:05:31Z,1920,How to make a chain of function decorators in ...,<p>How can I make two decorators in Python tha...
116,38987,3207.0,2008-09-02T07:44:30Z,1867,How to merge two Python dictionaries in a sing...,"<p>I have two Python dictionaries, and I want ..."
3216,613183,2786.0,2009-03-05T00:49:05Z,1837,Sort a Python dictionary by value,<p>I have a dictionary of values read from two...
1175,273192,13055.0,2008-11-07T18:56:45Z,1739,How to check if a directory exists and create ...,<p>What is the most elegant way to check if th...